version: '3'
services:
  postgres_db:
    image: postgres:16.3-alpine3.20
    container_name: postgres_db
    env_file: .env
    environment:
      POSTGRES_USER: $V_PG_DB_USER
      POSTGRES_PASSWORD: $V_PG_DB_PASSWORD
      POSTGRES_DB: $V_PG_DB_NAME
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  tg-vac3001-notifier:
    container_name: tg-vac3000-notifier
    image: toribash/vac-search-3001:noti
    env_file: .env
    depends_on:
      - postgres_db
    environment:
      - TELEGRAM_BOT_TOKEN=$V_TELEGRAM_BOT_TOKEN
      - PG_DB_NAME=$V_PG_DB_NAME
      - PG_DB_USER=$V_PG_DB_USER
      - PG_DB_PASSWORD=$V_PG_DB_PASSWORD
      - PG_DB_HOST=$V_PG_DB_HOST
    restart: always

  vac3001:
    container_name: vac3001-main
    image: toribash/vac-search-3001:main
    env_file: .env
    depends_on:
      - postgres_db
    environment:
      - USER_ID=$V_USER_ID
      - QUERY_ID=$V_QUERY_ID
      - DB_NAME=$V_PG_DB_NAME
      - DB_USER=$V_PG_DB_USER
      - DB_PASS=$V_PG_DB_PASSWORD
      - DB_HOST=$V_PG_DB_HOST