FROM alpine:latest

ENV PYTHONUNBUFFERED=1

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python

RUN python3 -m ensurepip

RUN pip3 install --no-cache --upgrade pip setuptools

RUN git clone https://github.com/toribasho/vacancy-searcher-3000.git

RUN pip install --no-cache-dir -r /vacancy-searcher-3000/requirements.txt

WORKDIR /vacancy-searcher-3000

CMD ["python3", "vacancy_searcher_3000.py"]